Set up associations
Chaseknis/OOP_school_library pull request #3
Opened 2023-04-12 22:55 UTC by Chaseknis

- Add `classroom.rb` file
- Add `rental.rb` file
- Add `book.rb`
- Implement `many-to-many` relationship
- Implement `has-many`/`belongs-to`, 
- Update`student.rb` file
- Update `person.rb` file
- Update `README.md` file
- Run `linters` for errors

2023-04-12 23:12 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️ ♻️ ♻️

Hi @Chaseknis,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ You used Gitflow correctly 👍🏽 
✅ Linter checks passed 👍🏽

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-04-12 23:12 UTC, AmaduKamara commented on student.rb
>    end
- [ ] This class is expected to have a classroom method that serves as the 'belongs-to' side (a student belongs to a classroom). Kindly add that 👍🏽

2023-04-12 23:12 UTC, AmaduKamara commented on book.rb
> +  # Other methods of Book class
- [ ] For this class, a method for adding rentals is required so rentals can be added. Kindly add that 👍🏽

2023-04-12 23:59 UTC, tufoinnkuo10 requested changes
Hi @Chaseknis 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Gitflow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ associations created well

Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/QW9DYS2fsdORhO9Phu/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-04-12 23:59 UTC, tufoinnkuo10 commented on student.rb
> +    super(name: name, age: age, parent_permission: parent_permission)
- [ ] please like the previous reviewer noted there shoudl be method that serves as the 'belongs-to' side (a student belongs to a classroom)
eg 
```ruby
def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
```

2023-04-13 00:10 UTC, algerina approved these changes
Hi  @Chaseknis  ,

Great job so far team! 

May I highlight the following: 
- [x] Your PR is descriptive✔️ 
- [x] Well done implementing all the requirements✔️ 


## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:

Your project is complete!  It's time to merge it :shipit:

<img src="https://media4.giphy.com/media/l7fdqmHQ1jCg2HzQlx/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-04-13 00:12 UTC, Chaseknis commented
thank you @algerina

2023-04-13 00:12 UTC, merged